
if [ -z "$NUM_PROC" ]; then
  echo "Defaulting to --parallel=1; set NUM_PROC to use more"
  NUM_PROC=1
fi

rm -rf $ARROW_BUILD && mkdir $ARROW_BUILD
cd $ARROW_BUILD && \
  cmake \
  -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_BUILD_TYPE=Debug \
  -DARROW_COMPUTE=ON \
  -DARROW_CSV=ON \
  -DARROW_DATASET=ON \
  -DARROW_EXTRA_ERROR_CONTEXT=ON \
  -DARROW_FILESYSTEM=ON \
  -DARROW_JEMALLOC=ON \
  -DARROW_JSON=ON \
  -DARROW_PARQUET=ON \
  -DARROW_WITH_SNAPPY=ON \
  -DARROW_WITH_ZLIB=ON \
  -DARROW_MIMALLOC=ON \
  -DARROW_S3=ON \
  -DARROW_TESTING=ON \
  -DARROW_SUBSTRAIT=ON \
  -DARROW_WITH_BROTLI=ON \
  -DARROW_WITH_BZ2=ON \
  -DARROW_WITH_LZ4=ON \
  -DARROW_WITH_SNAPPY=ON \
  -DARROW_WITH_ZSTD=ON \
  $ARROW_SOURCE/cpp && \
  cmake --build . --parallel=$NUM_PROC && \
  cmake --install . --prefix $ARROW_HOME

R CMD INSTALL $ARROW_SOURCE/r --preclean
